### ISSUE TITLE
AtomicParsley not found

### ISSUE THREAD

**Issue by unikitty37** [JamesBarwell/docker-get-iplayer#1]
After downloading a video, the following warning is displayed:

```
WARNING: Required AtomicParsley utility not found - cannot tag MP4 file
```

Would it be possible to have AtomicParsley installed as part of the image so that the file can be auto-tagged?

**Comment by JamesBarwell** [comment]
Hi, thanks for raising this. I've added AtomicParsley in the latest version `3.25.1`.

I did a quick test and it seems to tag successfully:
```
INFO: Downloaded: 201.38 MB (00:05:08) @ 35.02 Mb/s (hvfhd1/bi) [audio+video]
INFO: Converting to MP4
INFO: Tagging MP4
```
