### ISSUE TITLE
AtomicParsley utility not found

### ISSUE THREAD

**Issue by ahmgithubahm** [JamesBarwell/docker-get-iplayer#2]
Maybe a reoccurrence of #1 ?
I'm seeing this with the 3.27 build:
```INFO: Converting to M4A
WARNING: Required AtomicParsley utility not found - cannot tag M4A file
```

Anything I can do to help diagnose?  Thanks, Andy

**Comment by hepto** [comment]
It seems `get_iplayer` (now?) requires the AtomicParsley binary to be capitalised as such, and the installed version isn't.

I [solved this](https://github.com/hepto/c120/commit/e59bb3d9c5768055b07b98fef4124db779964efc) by simply symlinking it in the `Dockerfile`, as profile aliasing seemed to be more complicated and less portable.

    RUN ln -s `which atomicparsley` /usr/local/bin/AtomicParsley

Would be interested if there is a smarter solution.

**Comment by hepto** [comment]
I guess you can also simply tell `get_iplayer` where/what the `atomicparsley` binary is via an argument `--atomicparsley`, but for my project I’m calling it in multiple places so I wanted to set it once, plus if the pkg changes then it should continue to work.

**Comment by JamesBarwell** [comment]
Thanks. Good suggestion on the symlink. I've added it and republished as version `3.27.1`. Cheers.
